name: Deploy an application to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Update ECS Service for WordPress
        env:
          ECS_CLUSTER_NAME: ${{ secrets.ECS_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
          ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
          WORDPRESS_IMAGE_URI: ${{ secrets.IMAGE_URI }}
        run: |
          echo "Fetching current task definition for WordPress..."
          TASK_DEFINITION_JSON=$(aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION)
          echo "Current Task Definition: $TASK_DEFINITION_JSON"

          echo "Fetching current container definitions for WordPress..."
          CONTAINER_DEFINITIONS=$(echo $TASK_DEFINITION_JSON | jq '.taskDefinition.containerDefinitions')
          echo "Current Container Definitions: $CONTAINER_DEFINITIONS"

          echo "Updating container definitions with new WordPress image..."
          UPDATED_CONTAINER_DEFINITIONS=$(echo $CONTAINER_DEFINITIONS | jq '[.[] | if .name == "webapp" then .image = "'$WORDPRESS_IMAGE_URI'" else . end]')
          echo "Updated Container Definitions: $UPDATED_CONTAINER_DEFINITIONS"

          echo "Registering updated task definition for WordPress..."
          TASK_DEFINITION_FAMILY=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.family')
          EXECUTION_ROLE_ARN=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.executionRoleArn')
          TASK_ROLE_ARN=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.taskRoleArn')
          NETWORK_MODE=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.networkMode')
          CPU=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.cpu')
          MEMORY=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.memory')
          REQUIRES_COMPATIBILITIES=$(echo $TASK_DEFINITION_JSON | jq -r '.taskDefinition.requiresCompatibilities | join(",")')
          UPDATED_TASK_DEFINITION=$(aws ecs register-task-definition \
            --family $TASK_DEFINITION_FAMILY \
            --execution-role-arn $EXECUTION_ROLE_ARN \
            --task-role-arn $TASK_ROLE_ARN \
            --network-mode $NETWORK_MODE \
            --cpu $CPU \
            --memory $MEMORY \
            --requires-compatibilities $REQUIRES_COMPATIBILITIES \
            --container-definitions "$UPDATED_CONTAINER_DEFINITIONS" \
            --query "taskDefinition.taskDefinitionArn" --output text)
          echo "Updated Task Definition ARN: $UPDATED_TASK_DEFINITION"

          echo "Updating ECS service for WordPress..."
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $UPDATED_TASK_DEFINITION
